### ISSUE TITLE
how to use this in UITableview?

### ISSUE THREAD

**Issue by furueili** [DaidoujiChen/DaiDodgeKeyboard#7]
if I have some custom tableviewcell , and every cell has his own uitextfield,
how to use?

**Comment by DaidoujiChen** [comment]
Hello @furueili,

Do you ever try branch [demo-yolua](https://github.com/DaidoujiChen/DaiDodgeKeyboard/tree/hotfix/demo-yolua). It is I made for other friend. :)

**Comment by furueili** [comment]
I test the demo-yolua project , but it is not worked....,

no see any toolbar show, please help thx

**Comment by DaidoujiChen** [comment]
Hello @furueili,

I think you might have some misunderstood. `DaiDodgeKeyboard` is work for avoid the keyboard cover input views. If you want to add the `ToolBar` for each textfield. You have to do it yourself.

For an earlier question, `DaiDodgeKeyboard` only demo it can avoid the keyboard in the scrollview or tableview, thanks.

**Comment by furueili** [comment]
got it thx
