### ISSUE TITLE
When UTextfield Focused,tableview will be cut

### ISSUE THREAD

**Issue by furueili** [DaidoujiChen/DaiDodgeKeyboard#8]
issue like following screenshot

Could u give me some help ,  thx

![img_0135](https://cloud.githubusercontent.com/assets/1407724/8565412/4c49808c-2588-11e5-9a96-9a400533ffb0.PNG)

**Comment by DaidoujiChen** [comment]
Hello @furueili,
1. Are you using `DaiDodgeKeyboard` cause this issue?
2. Would you please provide sample code for us to reproduce this issue?

**Comment by furueili** [comment]
hihi~ @DaidoujiChen ,

1.YES, I use DaiDodgeKeyboard in UITableview from my custom form

2.Un..It's not convent, I just put some UITextfields in my custom UITableViewCell and when I touch textfield , the tableview will scroll and the  result comes...
